#! /bin/sh

INCLUDE="mkl05z4.s start.s lab3.s"
OUTFILE=""
BUILDDIR="build"

if [ ! -d "$BUILDDIR" ] ; then
    echo "Creating... $BUILDDIR/"
    mkdir "$BUILDDIR"
fi

for i in $INCLUDE; do
    echo "Assembling... $i"
    echo -en "\033[33m"
    arm-none-eabi-as -ahndl -g -o "$BUILDDIR/${i%.s}.o" "$i" > "$BUILDDIR/${i%.s}.lst"
    echo -en "\033[0m"
    OUTFILE="$OUTFILE $BUILDDIR/${i%.s}.o"
done

echo "Linking..."

echo -en "\033[33m"
arm-none-eabi-ld -o "$BUILDDIR/out.elf" -T linker.ld $OUTFILE -Map "$BUILDDIR/out.map"
arm-none-eabi-objdump -S "$BUILDDIR/out.elf" > "$BUILDDIR/out.dmp"
echo -en "\033[0m"

echo "Generating binary..."

echo -en "\033[33m"
arm-none-eabi-objcopy -O binary "$BUILDDIR/out.elf" "$BUILDDIR/out.bin"
echo -en "\033[0m"
